# Generated by Django 2.1.4 on 2018-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181216_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorit',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='webapp.Article'),
        ),
    ]
