# Generated by Django 2.1.4 on 2018-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20181216_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorit',
            field=models.ManyToManyField(related_name='favorites', to='webapp.Article'),
        ),
    ]
